version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "20:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "20:00"
      timezone: Asia/Tokyo
