version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      dev-deps:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
