name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    uses: ybiquitous/.github/.github/workflows/dependabot-auto-merge-reusable.yml@cdefa43486604b3aae79e9d1db24b670475f2c92 # v3.2.0
    permissions:
      contents: write
