name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    uses: ybiquitous/.github/.github/workflows/dependabot-auto-merge-reusable.yml@5e88270a455e5daf2387974dcb3cdea448076387 # v3.2.2
    permissions:
      contents: write
