name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: ybiquitous/.github/.github/workflows/nodejs-release-reusable.yml@6449c410d1b8ad8f7f6ac9e270441321ee65a5f6 # v3.0.1
    permissions:
      contents: write
      id-token: write
