name: Release PR

on:
  workflow_dispatch:
    inputs:
      new-version:
        description: New version to release
        required: true
        type: choice
        options: [auto, patch, minor, major]

jobs:
  release:
    uses: ybiquitous/.github/.github/workflows/nodejs-release-pr-reusable.yml@6449c410d1b8ad8f7f6ac9e270441321ee65a5f6 # v3.0.1
    with:
      new-version: ${{ github.event.inputs.new-version }}
    permissions:
      contents: write
      pull-requests: write
